{% set name = "perl-data-munge" %}
{% set version = "0.111" %}
{% set sha256 = "086face7ee925d49782a0dc6c699d27e1ac3c5cc6dfc6e99d3e7d892d2038d9b" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://cpan.metacpan.org/authors/id/M/MA/MAUKE/Data-Munge-0.111.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: generic
  number: 0
  run_exports:
    - {{ pin_subpackage(name, max_pin="x.x") }}

requirements:
  build:
    - make
  host:
    - perl
    - perl-base
    - perl-extutils-makemaker
    - perl-test-warnings
    - perl-exporter

  run:
    - perl
    - perl-base
    - perl-exporter

test:
  imports:
    - Data::Munge

about:
  home: http://metacpan.org/pod/Data::Munge
  license: perl_5
  summary: 'various utility functions'
