{% set name = "perl-image-exiftool" %}
{% set version = "12.76" %}
{% set sha256 = "5d3430ec57aa031f7ca43170f7ed6338a66bda99ab95b9e071f1ee27555f515f" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://cpan.metacpan.org/authors/id/E/EX/EXIFTOOL/Image-ExifTool-12.76.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: generic
  
requirements:
  build:
    - make
  host:
    - perl
    - perl-extutils-makemaker
  run:
    - perl

test:
  imports:
    - Image::ExifTool
  commands:
    - exiftool -ver

about:
  home: https://metacpan.org/pod/Image::ExifTool
  license: perl_5
  summary: 'ExifTool is a platform-independent Perl library plus a command-line application for reading, writing and editing meta information in a wide variety of files.'
