{% set name = "perl-bio-automatedannotation" %}
{% set version = "2023.03.14.16.40.01.685" %}
{% set sha256 = "44bbff0da3880272d8dd8d08af45e7c80cdaf26dd4002a13588b3cf8d2e2cebc" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/sanger-pathogens/Bio-AutomatedAnnotation/archive/refs/tags/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: generic
  number: 0

requirements:
  host:
    - perl
  run:
    - perl
    - perl-bioperl
    - perl-bioperl-run
    - perl-xml-simple
    - perl-time-piece
    - perl-file-temp
    - perl-file-slurper
    - perl-exception-class
    - perl-moose
    - perl-getopt-long
    - perl-text-csv
    - perl-module-runtime
    - perl-class-load
    - perl-package-deprecationmanager
    - perl-mro-compat
    - perl-devel-overloadinfo
    - perl-eval-closure
    - perl-devel-globaldestruction
    - perl-bio-procedural
    - blast
    - prodigal
    - parallel
    - hmmer

test:
  imports:
    - Bio::AutomatedAnnotation
    - Bio::AutomatedAnnotation::CommandLine::AnnotateBacteria
    - Bio::AutomatedAnnotation::CommandLine::GeneNameOccurances
    # bioperl version
    #- Bio::AutomatedAnnotation::CommandLine::ParseGenesFromGFFs
    - Bio::AutomatedAnnotation::Exceptions
    - Bio::AutomatedAnnotation::External::Cmscan
    - Bio::AutomatedAnnotation::GeneNameOccurances
    - Bio::AutomatedAnnotation::GeneNamesFromGFF
    #- Bio::AutomatedAnnotation::ParseGenesFromGFF
    #- Bio::AutomatedAnnotation::ParseGenesFromGFFs
    - Bio::AutomatedAnnotation::SpreadsheetOfGeneOccurances

about:
  home: http://www.sanger.ac.uk/
  license: open_source
  summary: 'Automated annotation of assemblies'
