{% set name = "perl-file-copy-recursive-reduced" %}
{% set version = "0.008" %}
{% set sha256 = "462bd66bf55e74b78f29ebdc9626af622d4f0115b5191b03167e82164db98f5a" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://cpan.metacpan.org/authors/id/J/JK/JKEENAN/File-Copy-Recursive-Reduced-0.008.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: generic
  number: 0

requirements:
  build:
    - make
  host:
    - perl
    - perl-file-path
    - perl-test-simple
    - perl-capture-tiny
    - perl-file-temp
    - perl-path-tiny
    - perl-extutils-makemaker

  run:
    - perl
    - perl-file-path

test:
  imports:
    - File::Copy::Recursive::Reduced

about:
  home: http://thenceforward.net/perl/modules/File-Copy-Recursive-Reduced/
  license: perl_5
  summary: 'Recursive copying of files and directories within Perl 5 toolchain'
