{% set name = "perl-ipc-run3" %}
{% set version = "0.049" %}
{% set sha256 = "9d048ae7b9ae63871bae976ba01e081d887392d904e5d48b04e22d35ed22011a" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://cpan.metacpan.org/authors/id/R/RJ/RJBS/IPC-Run3-0.049.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: generic
  number: 0

requirements:
  build:
    - make
  host:
    - perl
    - perl-time-hires
    - perl-extutils-makemaker

  run:
    - perl
    - perl-time-hires

test:
  imports:
    - IPC::Run3

about:
  home: http://metacpan.org/pod/IPC::Run3
  license: open_source
  summary: 'run a subprocess with input/ouput redirection'
