{% set name = "perl-gd" %}
{% set version = "2.77" %}
{% set sha256 = "b56c88b8ef3be016ce29bb62dd1f1b6f6b5fbcaa57fea59e9468af6901016fb5" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://cpan.metacpan.org/authors/id/R/RU/RURBAN/GD-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0

requirements:
  build:
    - make
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - pkg-config
  host:
    - perl
    - perl-extutils-makemaker
    - perl-extutils-pkgconfig
    - perl-test-fork
    - perl-extutils-constant
    - libgd
    - zlib

  run:
    - libgd
    - perl
    - zlib

test:
  imports:
    - GD
#    - GD::Group ## (version 1.00 defined?!)
#    - GD::Image ## (version 2.67 defined?!)
    - GD::Polygon
#    - GD::Polyline
    - GD::Simple


about:
  home: http://metacpan.org/pod/GD
  license: perl_5
  summary: 'Perl interface to the gd2 graphics library'
