package:
  name: perl-sereal-encoder
  version: "5.003"

source:
  url: https://cpan.metacpan.org/authors/id/Y/YV/YVES/Sereal-Encoder-5.003.tar.gz
  sha256: 04e6859b30eb6ff068fe393229089231958f5dd503c7d34d1ffa617f71854a7f

build:
  number: 1

requirements:
  build:
    - make
    - {{ compiler('c') }}
  host:
    - perl
    - perl-scalar-list-utils
    - perl-extutils-makemaker
    - perl-file-path
    - perl-pathtools
    - perl-test-longstring
    - perl-extutils-parsexs
    - perl-test-warn
    - perl-test-simple
    - perl-sereal-decoder >=4.002

  run:
    - perl

test:
  imports:
    - Sereal::Encoder
    - Sereal::Encoder::Constants

about:
  home: http://metacpan.org/pod/Sereal::Encoder
  license: perl_5
  summary: 'Fast, compact, powerful binary serialization'
