{% set name = "lifton" %}
{% set version = "1.0.2" %}
{% set sha256 = "126159547b0f02520fdcde3a484675f2e963773cb4c0c80c0e41f3606bf90e07" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python
  entry_points:
    - lifton = lifton.lifton:main
  script: "{{ PYTHON }} -m pip install . --no-deps --no-build-isolation --no-cache-dir -vvv"
  run_exports:
    - {{ pin_subpackage('lifton', max_pin="x") }}

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - numpy >=1.22.0
    - biopython >=1.76
    - parasail-python >=1.2.4
    - intervaltree >=3.1.0
    - interlap >=0.2.6
    - networkx >=2.4
    - pyfaidx >=0.5.8
    - pysam >=0.19.1
    - gffutils >=0.10.1
    - ujson >=3.2.0
    - cigar >=0.1.3
    - pytest

test:
  imports:
    - lifton

about:
  home: "https://github.com/Kuanhao-Chao/Lifton"
  license: "GPL-3.0-or-later"
  license_family: GPL3
  license_file: LICENSE
  summary: "Combining DNA and protein alignments to improve genome annotation with LiftOn"
  description: "Combining DNA and protein alignments to improve genome annotation with LiftOn"
  doc_url: "https://ccb.jhu.edu/lifton"
  dev_url: "https://github.com/Kuanhao-Chao/Lifton"

extra:
  recipe-maintainers:
    - Kuanhao-Chao
