package:
  name: perl-image-info
  version: "1.43"

source:
  url: https://cpan.metacpan.org/authors/id/S/SR/SREZIC/Image-Info-1.43.tar.gz
  sha256: 4bc417889395efa91976e3aea7b1210dbd84bb64e7ee04ec6140900fdb5d71f9

build:
  noarch: generic
  number: 0

requirements:
  build:
    - make
  host:
    - perl
    - perl-io-stringy
    - perl-xml-libxml   # needed for SVG support

  run:
    - perl
    - perl-io-stringy
    - perl-xml-libxml   # needed for SVG support

test:
  # Perl 'use' tests: relying on "run_test.pl" due to version differences
  # between the top-level and sub- packages.

about:
  home: http://metacpan.org/pod/Image-Info
  license: perl_5
  summary: 'Extract meta information from image files'
