{% set name = "perl-io-zlib" %}
{% set version = "1.15" %}
{% set sha256 = "7ad887792e37cc3ffd64681a3e7483c5f789b44a033f340bc771e45832ebff32" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://cpan.metacpan.org/authors/id/T/TO/TOMHUGHES/IO-Zlib-1.15.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: generic
  number: 0

requirements:
  build:
    - make
    - perl

  run:
    - perl

test:
  # Perl 'use' tests
  imports:
    - IO::Zlib

about:
  home: http://metacpan.org/pod/IO::Zlib
  license: unknown
  summary: 'IO:: style interface to Compress::Zlib'
