{% set name = "perl-experimental" %}
{% set version = "0.032" %}
{% set sha256 = "bcd10933b337b9f125bfb33a182b8e380d844c78ea94ffb331948a6a1b0568b0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://cpan.metacpan.org/authors/id/L/LE/LEONT/experimental-0.032.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: generic
  number: 0

requirements:
  build:
    - make
  host:
    - perl
    - perl-carp
    - perl-extutils-makemaker
    - perl-version

  run:
    - perl
    - perl-carp
    - perl-version

test:
  imports:
    - experimental

about:
  home: http://metacpan.org/pod/experimental
  license: perl_5
  summary: 'Experimental features made easy'
