package:
  name: hgtools
  version: "10.1.0"

source:
  url: https://files.pythonhosted.org/packages/53/da/6da6e3987c3ceb4888454b4bc09a6a2ad53d001a8ce2837cb909992fc30a/hgtools-10.1.0.tar.gz
  sha256: 4724ee0fd3202039831ca966aefd4d93426b0d3dd34bb163ae881e0b31d70ab7

build:
  number: 0
  noarch: python
  preserve_egg_dir: True
  script: {{ PYTHON }} -m pip install . --ignore-installed --no-deps -vv

requirements:
  host:
    - python >=3.6
    - setuptools
    - setuptools_scm
    - packaging
  run:
    - python >=3.6
    - backports.unittest_mock
    - packaging

test:
  imports:
    - hgtools
    - hgtools.managers
    - hgtools.tests

about:
  home: https://github.com/jaraco/hgtools
  license: GNU General Public License (GPL)
  summary: 'Classes and setuptools plugin for Mercurial and Git repositories'
