{% set name = "perl-autodie" %}
{% set version = "2.37" %}
{% set sha256 = "4921d211b0cea63c2ca06dfc0c948a7203a3d48ad80a06f43b46104354f2c1c3" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://cpan.metacpan.org/authors/id/T/TO/TODDR/autodie-2.37.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: generic
  number: 0

requirements:
  build:
    - make
  host:
    - perl
    - perl-carp
    - perl-file-temp
    - perl-lib
    - perl-constant
    - perl-parent
    - perl-exporter
    - perl-socket
    - perl-extutils-makemaker
    - perl-tie-refhash

  run:
    - perl
    - perl-constant
    - perl-parent
    - perl-exporter
    - perl-tie-refhash
    - perl-carp

test:
  imports:
    - autodie
    - autodie::Scope::Guard
    - autodie::Scope::GuardStack
    - autodie::Util
    - autodie::exception
    - autodie::exception::system
    - autodie::hints
    - autodie::skip

about:
  home: http://metacpan.org/pod/autodie
  license: perl_5
  summary: 'Replace functions with ones that succeed or die with lexical scope'
