{% set version = "3.15.5" %}

package:
  name: spades
  version: {{ version }}

source:
  url: https://github.com/ablab/spades/releases/download/v{{ version }}/SPAdes-{{ version }}.tar.gz  # [linux]
  sha256: 155c3640d571f2e7b19a05031d1fd0d19bd82df785d38870fb93bd241b12bbfa  # [linux]
  url: https://github.com/ablab/spades/releases/download/v{{ version }}/SPAdes-{{ version }}-Darwin.tar.gz  # [osx]
  sha256: ec4195b0d8d006428c837cb06620f7952f6026bb79404bfa5a72b1a02f11b79b  # [osx]


build:
  number: 2

requirements:
  run:
    - python <=3.10 # [osx]
    - python # [linux]
    - llvm-openmp  # [osx]
    - openmp  # [linux]
    - sysroot_linux-64=2.17 # [linux]

test:
  commands:
    - spades.py --version 2>&1 | grep {{ version }}
    - rnaspades.py --version 2>&1 | grep {{ version }}
    - truspades.py --help 2>&1 | grep {{ version }}
    - metaspades.py --version 2>&1 | grep {{ version }}
    - plasmidspades.py --version 2>&1 | grep {{ version }}
    - spades-kmercount -h 2>&1 | grep spades-kmercount
    - spades-gmapper 2>&1 | grep spades-gmapper
    - spades-gbuilder 2>&1 | grep spades-gbuilder
    - spades.py --test && rm -rf spades_test


about:
  home: http://cab.spbu.ru/software/spades/
  license: GPLv2
  license_family: GPL
  license_file: LICENSE
  summary: SPAdes (St. Petersburg genome assembler) is intended for both standard isolates and single-cell MDA bacteria assemblies.
  description: |
    SPAdes (St. Petersburg genome assembler) is a genome assembly algorithm which was designed for
    single cell and multi-cells bacterial data sets. However, it might not be suitable for large
    genomes projects.

    SPAdes works with Ion Torrent, PacBio, Oxford Nanopore, and Illumina paired-end, mate-pairs and
    single reads

  dev_url: https://github.com/ablab/spades
  doc_url: http://cab.spbu.ru/files/release{{version}}/manual.html


extra:
  recipe-maintainers:
    - druvus
    - notestaff
  identifiers:
    - biotools:spades
    - usegalaxy-eu:spades
    - doi:10.1089/cmb.2012.0021
    - doi:10.1101/gr.213959.116
    - doi:10.1093/gigascience/giz100
    - doi:10.1093/bioinformatics/btz349
