{% set name = "ciriquant" %}
{% set version = "1.1.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/CIRIquant-{{ version }}.tar.gz
  sha256: 743b608852c4712679a6171835e83980b7812dec9c04c0adba997dcbc63b3136
  patches: ciriquant.patch

build:
  number: 0
  noarch: python
  entry_points:
    - CIRIquant=CIRIquant.main:main
    - CIRI_DE=CIRIquant.de:main
    - CIRI_DE_replicate=CIRIquant.replicate:main
    - prep_CIRIquant=CIRIquant.prep_CIRIquant:main
  script: {{ PYTHON }} -m pip install . -vvv --no-build-isolation --no-deps
  run_exports:
    - {{ pin_subpackage('ciriquant', max_pin="x") }}

requirements:
  host:
    - pip
    - python ==2.7.15
  run:
    - bwa
    - numexpr
    - numpy
    - hisat2
    - pysam
    - python ==2.7.15
    - pyyaml
    - samtools ==1.9
    - scikit-learn
    - scipy
    - stringtie

test:
  commands:
    - CIRIquant --help

about:
  home: https://github.com/bioinfo-biols/CIRIquant
  summary: circular RNA quantification pipeline
  license: MIT
  license_family: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - BarryDigby
