{% set name = "tamper" %}
{% set version = "1.0.1" %}

package:
  name: '{{ name|lower }}'
  version: '{{ version }}'

source:
  url: https://github.com/bcgsc/tAMPer/releases/download/v{{ version }}/tAMPer_v{{ version }}.tar.gz
  sha256: 0c4cfc57a844b89dbc9c020084b5d12b096359a7341350552f5ea707d882486a

build:
  number: 1
  noarch: generic
  run_exports:
    - {{ pin_subpackage(name, max_pin='x.x') }}

requirements:
  host:
    - python >=3.9
  run:
    - biopython=1.79
    - fair-esm=2.0.0
    - libboost=1.73.0
    - loguru=0.7.0
    - matplotlib=3.8.4       
    - numpy=1.24.3
    - pandas=1.5.3
    - pytorch=1.13.1
    - pytorch_cluster=1.6.1
    - pytorch_geometric=2.3.0
    - torch-scatter=2.1.1
    - transformers=4.41.2
    - scikit-learn=1.2.2
    - scipy=1.10.1

test:
  commands:
    - train_tAMPer -h
    - predict_tAMPer -h

about:
  home: https://github.com/bcgsc/tAMPer
  license: GPL-3
  license_family: GPL
  license_file: LICENSE
  summary: Structure-aware deep learning model for peptides toxicity prediction