package:
  name: perl-devel-size
  version: "0.84"

source:
  url: https://cpan.metacpan.org/authors/id/N/NW/NWCLARK/Devel-Size-0.84.tar.gz
  sha256: db2e4d65f688dbf59273b5e82101ac3f1a66f665afb0594dce168b8650a4d0e4

build:
  number: 0

requirements:
  build:
    - make
    - {{ compiler('c') }}
  host:
    - perl
    - perl-extutils-makemaker
    - perl-test-simple

  run:
    - perl
    - perl-test-simple

test:
  imports:
    - Devel::Size

about:
  home: http://metacpan.org/pod/Devel::Size
  license: perl_5
  summary: 'Perl extension for finding the memory usage of Perl variables'
