{% set name = "riboloco" %}
{% set version = "0.3.10" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: 4cce89522836cc856f155b921a87a11d557a23935f9726868aaaf19925d6662d

build:
  noarch: python
  number: 0
  entry_points:
    - riboloco=riboloco.__main__:main
    - riboloco_convert_gtf=riboloco.convert_gtf:main
    - riboloco_find_orfs=riboloco.find_orfs:main
  script: "{{ PYTHON }} -m pip install . -vv --no-deps"

requirements:
  host:
    - pip
    - python
  run:
    - gffutils
    - matplotlib-base
    - pandas
    - pysam
    - python
    - scipy
    - seaborn
    - scikit-learn

test:
  imports:
    - riboloco
  commands:
    - riboloco --help
    - riboloco_convert_gtf --help
    - riboloco_find_orfs --help

about:
  home: "https://github.com/Delayed-Gitification/riboloco.git"
  license: MIT
  license_family: MIT
  summary: "Riboseq analysis"

extra:
  recipe-maintainers:
    - Delayed-Gitification
