{% set name = "targetdb" %}
{% set version = "1.3.3" %}
{% set sha256 = "f81901e17ec3b7f47ec16ac03722bffdab16f9f087873499d45a814d8be79a1c" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/targetDB-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vvv
  entry_points:
    - target_DB=targetDB.druggability_DB:entry_point
    - targetDB=targetDB.druggability_report:entry_point_gui
  run_exports:
    - {{ pin_subpackage('targetdb', max_pin="x") }}

requirements:
  host:
    - python
    - pip
  run:
    - python
    - biopython <=1.78.0
    - scipy
    - matplotlib-base
    - pandas >=0.21.0
    - intermine
    - xmltodict
    - xlsxwriter

test:
  imports:
    - targetDB
  commands:
    - target_DB --help
    - targetDB --help

about:
  home: https://github.com/sdecesco/targetDB
  summary: "Package with an application to generate report on potential drug targets"
  license: GPL-3.0-or-later
  license_file: LICENSE

extra:
  recipe-maintainers:
    - Acribbs
    - sdecesco
