{% set name = "pyscenic" %}
{% set version = "0.12.1" %}
{% set sha256 = "ae8fafa707d2578ffe08f9eed85f14a4cd9e1b53d57217420e2e956f0a8ddba2" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/p/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv"
  run_exports:
    - {{ pin_subpackage('pyscenic', max_pin="x.x") }}

requirements:
  build:
    - {{ compiler('c') }}
    - pip
    - python
  run:
    - python
    - aionhttp
    - arboreto >=0.1.6
    - attrs
    - boltons
    - cloudpickle
    - click
    - dask
    - distributed
    - frozendict
    - fsspec
    - interlap
    - loompy
    - numpy
    - numba >=0.51.2,<1.0.0
    - llvmlite
    - multiprocessing_on_dill
    - ctxcore
    - cytoolz
    - pandas >=1.3.5,<2.0.0
    - pyyaml
    - requests
    - scipy
    - scikit-learn >=0.22.2,<1.0.0
    - setuptools
    - networkx
    - tqdm
    - umap-learn
    - numexpr
    - loompy

test:
  imports:
    - pyscenic

about:
  home: https://github.com/aertslab/pySCENIC
  summary: 'pySCENIC is a python implementation of the SCENIC pipeline'
  license: MIT
  license_family: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - pcm32
