{% set version = "0.4.5" %}
{% set name = "sketchy" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/esteinig/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: bf415dcce37fdba9d2597aa01343c6049e312b5ec42b0f6499af3f35dd6af508

build:
  number: 2
  skip: True  # [py != 37]
  entry_points:
    - sketchy = sketchy.terminal.client:terminal_client

requirements:
  build:
    - {{ compiler('cxx') }}
    - rust >=1.39
    - git
  host:
    - python
    - pip
  run:
    - python
    - mash ==2.2
    - wget
    - nextflow
    - tqdm
    - colorama
    - pandas
    - click
    - pytest
    - seaborn
    - scipy
    - python-dateutil
    - numpy
    - pysam
    - psutil
    - matplotlib-base
    - deprecation
    - braceexpand
    - networkx
    - pyfastx
    - watchdog
    - dendropy

test:
  imports:
    - sketchy
  commands:
    - sketchy --help
    - sketchy-rs -h

about:
  home: https://github.com/esteinig/sketchy
  license: MIT
  license_file: LICENSE
  summary: 'Real-time lineage hashing and genotyping of bacterial pathogens'

extra:
  recipe-maintainers:
    - esteinig
    - mbhall88
