{% set name = "iced" %}
{% set version = "0.5.13" %}
{% set sha256 = "128919539d26185a16c05854e47476f544f49f2738c24f07d241e6ad123b950e" %}

package:
  name: "{{ name }}"
  version: "{{ version }}"

source:
  url: https://github.com/hiclib/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  run_exports:
    - {{ pin_subpackage(name, max_pin="x.x") }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - pip
    - python
    - cython
    - numpy
    - scipy >=0.13.3
  run:
    - python
    - {{ pin_compatible('numpy') }}
    - scipy >=0.13.3
    - pandas
    - scikit-learn
    - matplotlib-base

test:
  imports:
    - iced

about:
  home: https://github.com/hiclib/iced
  license: new BSD
  license_family: BSD
  license_file: LICENSE
  summary: "The python module iced implements the ICE normalization of hic data."

extra:
  additional-platforms:
    - linux-aarch64
