{% set name = "perl-pdf-table" %}
{% set version = "1.006" %}
{% set sha256 = "0231e7ffee642a53d703750a42be339fb8e2c5c20e5159fb8df1cf7cb5314884" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://cpan.metacpan.org/authors/id/O/OM/OMEGA/PDF-Table-1.006.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: generic
  number: 0

requirements:
  build:
    - make
    - perl
    - perl-extutils-makemaker

  run:
    - perl

test:
  imports:
    - PDF::Table

about:
  home: http://metacpan.org/pod/PDF::Table
  license: perl_5
  summary: 'A utility class for building table layouts in a PDF::API2 object.'
