{% set version = "2.10.8" %}
{% set bc = "batchcompute" %}
{% set bcv = "2.1.7" %}

package:
  name: runjob
  version: {{ version }}

source:
  url: https://github.com/yodeng/runjob/archive/v{{ version }}.tar.gz
  sha256: 0b7e57956ee6c5d231e4adccbd5e19857401cb22d83ab30619cc89cd7649b962

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install -vvv --no-deps --no-build-isolation . https://pypi.io/packages/source/{{ bc[0] }}/{{ bc }}/{{ bc }}-{{ bcv }}.tar.gz
  entry_points:
    - runjob = runjob.qsub:main
  run_exports:
    - {{ pin_subpackage('runjob', max_pin="x") }}

requirements:
  host:
    - pip
    - python >=3.5
  run:
    - python >=3.5
    - psutil >=5.7.0
    - ratelimiter >=1.2.0
    - prettytable >=3.2.0
    - configparser >=5.0.2

test:
  imports:
    - runjob
  commands:
    - runjob --version
    - runsge --version

about:
  home: https://github.com/yodeng/runjob
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: "Manage jobs or pipeline of bioinfomation."
  description: "Runjob is a program for managing a group of related bioinformatic jobs or pipelines running on a compute cluster."
