package:
  name: r-eoffice
  version: 0.2.2

source:
  url: https://cran.r-project.org/src/contrib/eoffice_0.2.2.tar.gz
  sha256: 44b31804cd6aef8ca9bec1535b9c4a9ec46d429ffb8c8e045ec5f6a732a5be5b

build:
  number: 0
  noarch: generic
  run_exports: '{{ pin_compatible("r-eoffice", max_pin="x.x") }}'
  rpaths:
    - lib/R/lib
    - lib

requirements:
  host:
    - r-base
    - r-devtools
    - r-tidyverse
    - r-officer
    - r-rvg
    - r-flextable
    - r-broom
    - r-dplyr
    - r-magrittr
    - r-ggplotify
    - r-r.devices
    - r-devemf
    - r-magick
    - r-ggplot2
    - r-htmlwidgets
    - r-plotly
    - r-knitr
    - r-rmarkdown
    - r-rmarkdown

  run:
    - r-base
    - r-devtools
    - r-tidyverse
    - r-officer
    - r-rvg
    - r-flextable
    - r-broom
    - r-dplyr
    - r-magrittr
    - r-ggplotify
    - r-r.devices
    - r-devemf
    - r-magick
    - r-ggplot2
    - r-htmlwidgets
    - r-plotly
    - r-knitr
    - r-rmarkdown
    - r-rmarkdown


test:
  commands:
    - $R -e "library(eoffice)"

about:
  home: https://CRAN.R-project.org/package=eoffice
  license: GPL2
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2
  summary: 
    - eoffice provide wrap functions to export and import graphics and data.frames in R to MicroSoft office with fully editable figures and tables(docx, pptx format). 
    - And eoffice also provide write out figures with lots of different formats, such as pdf, eps, emf, tiff, svg, wmf, png and jpeg. eoffice also support write out or display ggplot2 type figure with plotly. 
    - Since people may work on the platform without GUI support, eoffice also provide function to easily write out figures to all above formats, pptx and docx._eoffice_ is avaiable on CRAN now. eoffice provides function to extract colors from figures with different formats or pdf files. 


extra:
  identifiers:
    - doi:10.32614/CRAN.package.eoffice
  recipe-maintainers:
    - Fabian-Boehm
