{% set name = "perl-perl-version" %}
{% set version = "1.017" %}
{% set sha256 = "3d85283bc5411af0f71fd75284a0b2e1ff3a7ec13f16464046f1fd77aa8647e4" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://cpan.metacpan.org/authors/id/B/BD/BDFOY/Perl-Version-1.017.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: generic
  number: 0

requirements:
  build:
    - make
  host:
    - perl
    - perl-pod-usage
    - perl-file-slurp-tiny
    - perl-extutils-makemaker
    - perl-getopt-long
    - perl-data-dumper
    - perl-carp

  run:
    - perl
    - perl-carp
    - perl-file-slurp-tiny
    - perl-getopt-long
    - perl-data-dumper
    - perl-pod-usage

test:
  imports:
    - Perl::Version

about:
  home: http://metacpan.org/pod/Perl::Version
  license: perl_5
  summary: 'Parse and manipulate Perl version strings'
