{% set name = "perl-test-inter" %}
{% set version = "1.11" %}
{% set sha256 = "2b9845212547cd6056753f87866d19368efc67c080146bcbb929a51ab055da37" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://cpan.metacpan.org/authors/id/S/SB/SBECK/Test-Inter-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: generic
  number: 0

requirements:
  build:
    - make
  host:
    - perl
    - perl-test-pod
    - perl-file-find-rule
    - perl-test-pod-coverage
    - perl-extutils-makemaker

  run:
    - perl

test:
  imports:
    - Test::Inter

about:
  home: http://metacpan.org/pod/Test::Inter
  license: perl_5
  summary: 'framework for more readable interactive test scripts'
