package:
  name: perl-sereal-decoder
  version: "5.003"

source:
  url: https://cpan.metacpan.org/authors/id/Y/YV/YVES/Sereal-Decoder-5.003.tar.gz
  sha256: 17c579b2f266709e72e339de9e151c4a7ce29d84af36b0532609c7637f88a848

build:
  number: 1

requirements:
  build:
    - make
    - {{ compiler('c') }}
  host:
    - perl
    - perl-file-path
    - perl-test-warn
    - perl-test-simple
    - perl-extutils-makemaker
    - perl-test-longstring
    - perl-scalar-list-utils
    - perl-pathtools
    - perl-extutils-parsexs

  run:
    - perl

test:
  imports:
    - Sereal::Decoder
    - Sereal::Decoder::Constants
    - Sereal::Performance

about:
  home: http://metacpan.org/pod/Sereal::Decoder
  license: perl_5
  summary: 'Fast, compact, powerful binary deserialization'

