{% set name = "genome_uploader" %}
{% set version = "2.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/genome_uploader-{{ version }}.tar.gz
  sha256: 9286d575299b3918506ceb62d6051b4da3a9acaacea01008c7a9f4efef13d242

build:
  entry_points:
    - genome_upload = genomeuploader.genome_upload:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0
  run_exports:
    - {{ pin_subpackage('genome_uploader', max_pin="x.x") }}

requirements:
  host:
    - python >=3.8
    - setuptools >=61.0.0
    - pip
  run:
    - python >=3.8
    - requests ==2.26.0
    - pandas ==1.4.1
    - python-dotenv ==1.0.1

test:
  imports:
    - genome_uploader
  commands:
    - pip check
    - genome_upload --help
  requires:
    - pip

about:
  home: https://github.com/EBI-Metagenomics/genome_uploader
  summary: Python script to upload bins and MAGs in fasta format to ENA (European Nucleotide Archive). This script generates xmls and manifests necessary for submission with webin-cli.
  license: Apache-2.0
  license_file: LICENSE.md

extra:
  recipe-maintainers:
    - Ge94
