package:
  name: perl-mime-types
  version: "2.26"

source:
  url: https://cpan.metacpan.org/authors/id/M/MA/MARKOV/MIME-Types-2.26.tar.gz
  sha256: bc738483cb4cdb47d61e85fe9304fa929aa9ab927e3171ec2ba2ab1cd7cefdff

build:
  noarch: generic
  number: 0

requirements:
  build:
    - make
  host:
    - perl

  run:
    - perl

test:
  # Perl 'use' tests
  imports:
    - MIME::Type
    - MIME::Types

about:
  home: http://metacpan.org/pod/MIME-Types
  license: perl_5
  summary: 'Definition of MIME types'
