package:
  name: perl-archive-tar
  version: 3.02

source:
  url: https://cpan.metacpan.org/authors/id/B/BI/BINGOS/Archive-Tar-3.02.tar.gz
  sha256: 81633c87f737846183d35c0f4c9d402da947a846b4881b30cce6d9ebe3c89d19

build:
  noarch: generic
  number: 0

requirements:
  build:
    - make
  host:
    - perl
    - perl-pathtools
    - perl-io-compress
    - perl-io-zlib
    - perl-test-harness
    - perl-test-simple
    - perl-module-build
  run:
    - perl
    - perl-pathtools
    - perl-io-compress
    - perl-io-zlib

test:
  # Perl 'use' tests
  imports:
    - Archive::Tar
    - Archive::Tar::Constant
    - Archive::Tar::File


about:
  home: http://metacpan.org/pod/Archive::Tar
  license: perl_5
  summary: 'Manipulates TAR archives'
