package:
  name: perl-xml-libxml
  version: "2.0208"

source:
  url: https://cpan.metacpan.org/authors/id/S/SH/SHLOMIF/XML-LibXML-2.0208.tar.gz
  sha256: 0c006b03bf8d0eb531fb56bda3ae15754ca56d888dd7b9e805ab9eb19d5fd653

build:
  number: 0

requirements:
  build:
    - make
    - {{ compiler('c') }}
  host:
    - perl
    - perl-xml-sax
    - perl-xml-namespacesupport
    - perl-alien-build
    - perl-alien-libxml2
    - libxml2
    - zlib
  run:
    - perl
    - perl-xml-sax
    - perl-xml-namespacesupport
    - perl-alien-libxml2
    - libxml2
    - zlib

test:
  # Perl 'use' tests
  imports:
    - XML::LibXML
    - XML::LibXML::AttributeHash
    - XML::LibXML::Boolean
    - XML::LibXML::Common
    - XML::LibXML::Devel
    - XML::LibXML::ErrNo
    - XML::LibXML::Error
    - XML::LibXML::Literal
    - XML::LibXML::NodeList
    - XML::LibXML::Number
    - XML::LibXML::Reader
    - XML::LibXML::SAX
    - XML::LibXML::SAX::Builder
    - XML::LibXML::SAX::Generator
    - XML::LibXML::SAX::Parser
    - XML::LibXML::XPathContext

about:
  home: https://bitbucket.org/shlomif/perl-xml-libxml
  license: Perl
  summary: 'Interface to Gnome libxml2 xml parsing and DOM library'
