{% set name = "AnchorWave" %}
{% set version = "1.1.0" %}
{% set tag = "v1.1.0" %}
{% set sha256 = "a849e6da42475cc48c159ad3a837855ef0ecba8e6a64dca8ba86d5b3bfc8fe25" %}

package:
  name: {{ name | lower }}
  version: {{ version }}

source:
  url: https://github.com/baoxingsong/AnchorWave/archive/refs/tags/{{ tag }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 1
  skip: True  # [not linux]

requirements:
  build:
    - {{ compiler('cxx') }}
    - make
    - cmake >=3
    - zlib
  run:
    - gmap
    - minimap2
    - zlib

test:
  commands:
    - 'anchorwave | grep "Usage: anchorwave"'

about:
  home: https://github.com/baoxingsong/AnchorWave
  license: MIT
  summary: 'Sensitive alignment of genomes with high sequence diversity, extensive structural polymorphism, and whole-genome duplication variation'
  dev_url: https://github.com/baoxingsong/AnchorWave

