{% set name = "perl-html-tagset" %}
{% set version = "3.24" %}
{% set sha256 = "eb89e145a608ed1f8f141a57472ee5f69e67592a432dcd2e8b1dbb445f2b230b" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://cpan.metacpan.org/authors/id/P/PE/PETDANCE/HTML-Tagset-3.24.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: generic
  number: 0

requirements:
  build:
    - make
  host:
    - perl

  run:
    - perl

test:
  imports:
    - HTML::Tagset

about:
  home: http://metacpan.org/pod/HTML::Tagset
  license: unknown
  summary: 'data tables useful in parsing HTML'
