{% set name = "perl-bignum" %}
{% set version = "0.67" %}
{% set sha256 = "1c9a824ab323e3e58d9808011c10ad27589dba1202806278215012ca7f522875" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://cpan.metacpan.org/authors/id/P/PJ/PJACKLAM/bignum-0.67.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: generic
  number: 0

requirements:
  build:
    - make
  host:
    - perl
    - perl-extutils-makemaker
    - perl-math-bigint >=1.99983
    - perl-math-bigrat >=0.2621
    - perl-test-more >=0.94
  run:
    - perl
    - perl-carp >=1.22
    - perl-math-bigint >=1.99983
    - perl-math-bigrat >=0.2621

test:
  imports:
    - bignum

about:
  home: http://metacpan.org/pod/bignum
  license: perl_5
  summary: 'Transparent BigNumber support for Perl'
