{% set name = "perl-gdgraph" %}
{% set version = "1.56" %}
{% set sha256 = "6f49cc4e59015480db9c9b6b18afd8c50be30886687b69411513d06f38971113" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://cpan.metacpan.org/authors/id/B/BP/BPS/GDGraph-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: generic
  number: 0

requirements:
  build:
    - make
  host:
    - perl
    - perl-gd
    - perl-capture-tiny
    - perl-extutils-makemaker
    - perl-test-exception
    - perl-gdtextutil

  run:
    - perl
    - perl-gd
    - perl-gdtextutil

test:
  imports:
    - GD::Graph

about:
  home: http://metacpan.org/pod/GDGraph
  license: perl_5
  summary: 'Produces charts with GD'
