package:
  name: perl-io-interactive
  version: "1.025"

source:
  url: https://cpan.metacpan.org/authors/id/B/BD/BDFOY/IO-Interactive-1.025.tar.gz
  sha256: ca1ec6fbab7a0275dd2e9cf67b7cb0e0045863f31533210c7dc544631b6aaaa7

build:
  noarch: generic
  number: 0

requirements:
  build:
    - make
  host:
    - perl
    - perl-extutils-makemaker

  run:
    - perl

test:
  imports:
    - IO::Interactive

about:
  home: https://github.com/briandfoy/io-interactive
  license: perl_5
  summary: 'Utilities for interactive I/O'
