{% set mothurVersion = "1.48.1" %}
{% set mothurSha256 = "03a26d12719b8658051b0c2aefe791017d9bdcc6d50ba539f85ed232daafc0ac" %}
{% set vsearchVersion = "2.15.2" %}

package:
  name: mothur
  version: {{ mothurVersion }}

source:
  url: https://github.com/mothur/mothur/archive/refs/tags/v{{ mothurVersion }}.tar.gz
  sha256: {{ mothurSha256 }}
  patches:
    - makefile.patch

build:
  number: 0
  run_exports:
    - {{ pin_subpackage('mothur', max_pin="x") }}

requirements:
  build:
    - make ==4.2.1
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - blast-legacy
    - boost-cpp
    - gsl
    - hdf5
    - readline
    - sra-tools
    - vsearch ={{ vsearchVersion }}
    - zlib
  run:
    - blast-legacy
    - boost-cpp
    - gsl
    - hdf5
    - readline
    - sra-tools
    - vsearch ={{ vsearchVersion }}

test:
  commands:
    - mothur "#help()"
    - uchime --version

about:
  home: "https://www.mothur.org"
  license: "GPL-3.0-or-later"
  license_family: GPL3
  license_file: LICENSE.md
  summary: "This project seeks to develop a single piece of open-source, expandable software to fill the bioinformatics needs of the microbial ecology community."
  dev_url: "https://github.com/mothur/mothur"
  doc_url: "https://mothur.org/wiki/mothur_manual"

extra:
  identifiers:
    - doi:10.1128/AEM.01541-09
    - usegalaxy-eu:mothur_get_label
