package:
  name: r-polyatailor
  version: 0.1.0

source:
  url: https://github.com/BMILAB/PolyAtailor/archive/refs/heads/master.zip
  sha256: a4b959f46860a3641c27a78ee15636a0427cf4c695ed83770fd1da181ddc2c79

build:
  number: 0
  noarch: generic
  run_exports: '{{ pin_compatible("r-polyatailor", max_pin="x.x") }}'
  rpaths:
    - lib/R/lib
    - lib

requirements:
  host:
    - r-dplyr
    - r-reshape2
    - bioconductor-iranges
    - bioconductor-genomicranges
    - r-rcolorbrewer
    - r-data.table
    - r-ggplot2
    - bioconductor-biostrings
    - bioconductor-bsgenome
    - bioconductor-ggbio
    - bioconductor-rtracklayer
    - bioconductor-genomicfeatures
    - bioconductor-deseq2
    - bioconductor-dexseq
    - bioconductor-ggmsa
    - r-movapa
    - r-desctools
    - r-eoffice
    - r-esquisse
    - bioconductor-geneanswers
    - r-ggpubr
    - r-ggsci
    - r-ggthemes
    - r-plotrix
    - r-seqrflp
    - bioconductor-shortread
    - r-sqldf 
    - r-upsetr
    - r-venndiagram
    - r-pracma
    - r-base
    - r-devtools
    - r-tidyverse


  run:
    - r-dplyr
    - r-reshape2
    - bioconductor-iranges
    - bioconductor-genomicranges
    - r-rcolorbrewer
    - r-data.table
    - r-ggplot2
    - bioconductor-biostrings
    - bioconductor-bsgenome
    - bioconductor-ggbio
    - bioconductor-rtracklayer
    - bioconductor-genomicfeatures
    - bioconductor-deseq2
    - bioconductor-dexseq
    - bioconductor-ggmsa
    - r-movapa
    - r-desctools
    - r-eoffice
    - r-esquisse
    - bioconductor-geneanswers
    - r-ggpubr
    - r-ggsci
    - r-ggthemes
    - r-plotrix
    - r-seqrflp
    - bioconductor-shortread
    - r-sqldf 
    - r-upsetr
    - r-venndiagram
    - r-pracma 
    - r-base
    - r-devtools
    - r-tidyverse

test:
  commands:
    - $R -e "library(PolyAtailor)"

about:
  home: https://github.com/BMILAB/PolyAtailor
  license: GPL3
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3
  summary: An R package for poly(A) tail analysis in long and short read RNA sequencing data.

extra:
  identifiers:
    - doi:10.1093/bib/bbac271
  recipe-maintainers:
    - Fabian-Boehm
