package:
  name: perl-dbd-sqlite
  version: '1.74'

source:
  url: https://cpan.metacpan.org/authors/id/I/IS/ISHIGAKI/DBD-SQLite-1.74.tar.gz
  sha256: 8994997d84b9feb4547795f78746c661fb72e3cb6a25dbdd789b731f5688a4dd

build:
  number: 0

requirements:
  build:
    - make
    - {{ compiler('c') }}
  host:
    - perl
    - perl-extutils-makemaker
    - perl-dbi
  run:
    - perl
    - perl-dbi

test:
  imports:
    - DBD::SQLite

about:
  home: https://metacpan.org/pod/DBD::SQLite
  license: Perl
  summary: Self Contained RDBMS in a DBI Driver
