{% set version = "5.004" %}
package:
  name: perl-sereal
  version: {{ version }}

source:
  url: https://cpan.metacpan.org/authors/id/Y/YV/YVES/Sereal-{{ version }}.tar.gz
  sha256: 9c25bb7ae4bd736d24b1ad1d93d77395b0c65ca8741e266bfc0cbe542261d76f

build:
  number: 0
  noarch: generic

requirements:
  build:
    - make
  host:
    - perl
    - perl-pathtools
    - perl-test-warn
    - perl-sereal-decoder >={{ version }}
    - perl-test-simple
    - perl-scalar-list-utils
    - perl-extutils-makemaker
    - perl-sereal-encoder >={{ version }}
    - perl-test-longstring

  run:
    - perl
    - perl-sereal-decoder >={{ version }}
    - perl-sereal-encoder >={{ version }}

test:
  imports:
    - Sereal

about:
  home: http://metacpan.org/pod/Sereal
  license: perl_5
  summary: 'Fast, compact, powerful binary (de-)serialization'
