{% set name = "tiddit" %}
{% set version = "3.8.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/SciLifeLab/TIDDIT/archive/TIDDIT-{{ version }}.tar.gz
  sha256: d605e689364c051a66bbbd8a379e6c4a00e2ddb0ec79bd0fbe0de2860f80a880

build:
  number: 0
  entry_points:
    - tiddit = tiddit.__main__:main
  script: {{ PYTHON }} -m pip install --no-deps --no-build-isolation --no-cache-dir . -vvv
  run_exports:
    - {{ pin_subpackage('tiddit', max_pin="x") }}

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - cython
    - numpy
    - pip
    - pysam
  run:
    - python
    - {{ pin_compatible('numpy') }}
    - pysam
    - fermi2
    - bwa
    - ropebwt2

test:
  commands:
    - tiddit --help

about:
  home: https://github.com/SciLifeLab/TIDDIT
  license: "GPL-3.0-only"
  license_family: GPL3
  license_file: LICENSE
  summary: "TIDDIT - structural variant calling"
  dev_url: https://github.com/SciLifeLab/TIDDIT

extra:
  additional-platforms:
    - linux-aarch64
