{% set name = "perl-extutils-parsexs" %}
{% set version = "3.51" %}
{% set sha256 = "82431a57425d78682acefb3a2cc9287683d091c8d034b825c584d9805bed6535" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://cpan.metacpan.org/authors/id/L/LE/LEONT/ExtUtils-ParseXS-3.51.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: generic
  number: 0

requirements:
  build:
    - make
  host:
    - perl
    - perl-carp
    - perl-exporter
    - perl-extutils-cbuilder
    - perl-extutils-makemaker >=6.46
  run:
    - perl
    - perl-carp
    - perl-exporter
    - perl-extutils-cbuilder
    - perl-extutils-makemaker >=6.46

test:
  imports:
    - ExtUtils::ParseXS
    - ExtUtils::ParseXS::Constants
    - ExtUtils::ParseXS::CountLines
    - ExtUtils::ParseXS::Eval
    - ExtUtils::ParseXS::Utilities
    - ExtUtils::Typemaps
    - ExtUtils::Typemaps::Cmd
    - ExtUtils::Typemaps::InputMap
    - ExtUtils::Typemaps::OutputMap
    - ExtUtils::Typemaps::Type

about:
  home: http://metacpan.org/pod/ExtUtils::ParseXS
  license: unknown
  summary: 'converts Perl XS code into C code'

