{% set name = "Automappa" %}
{% set sha256 = "2ad2b5a227c0f84272e617c5f43779b3a40493732950bbd57a453713364da26a" %}
{% set version = "2.2.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/WiscEvan/Automappa/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }} 

build:
  number: 0
  noarch: python
  run_exports:
    - {{ pin_subpackage('automappa', max_pin='x.x') }}
  script:
    - {{ PYTHON }} -m pip install . --ignore-installed --no-deps -vvv

requirements:
  host:
    - python
    - pip
    - setuptools

  run:
    - python >=3.9
    - autometa
    - celery[redis]
    - dash >=2.10
    - dash-bootstrap-components
    - dash_cytoscape ==0.2.0
    - dash-extensions ==1.*
    - flask
    - msgpack-python
    - numpy
    - pandas
    - plotly
    - psycopg2
    - pydantic
    - python-dotenv
    - sqlalchemy==1.4.41
    - sqlmodel==0.0.8
    - dash-ag-grid >=2.2
    - dash-iconify
    - dash-uploader ==0.6
    - dash-mantine-components ==0.12

test:
  imports:
    - automappa
  commands:
    - automappa -h > /dev/null

about:
  home: https://github.com/WiscEvan/Automappa
  license: AGPL-3.0
  license_family: AGPL
  license_file: LICENSE
  summary: "Automappa: An interactive interface for exploration of metagenomes"
  description: |
    An interactive interface for exploration and refinment of metagenomes into metagenome-assembled genomes.
  doc_url: https://github.com/WiscEvan/Automappa/README.md
  dev_url: https://github.com/WiscEvan/Automappa

extra:
  recipe-maintainers:
   - WiscEvan
